language: objective-c
osx_image: xcode7.3
env:
  global:
  - SDK=iphonesimulator9.3
  - FRAMEWORK_NAME=Notify
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: NjtPAMAPBM8Bt1vECgmaNUThvkEawdY8typL9kpMPDtZvH3g8VhXcvGpb3LxpZkA/I5D9igtu6pvq3eJ8dYhQEUEI/Gu+Tv2NWMIEy5htchIrB5Po0PhuTnHZHb4mh/IE4hd/Pmnk2mpaIYYZyBQ1VmavYKsK/SLfrk3iqHHXSwX59eiu3CECbKJAqXjdljTfAFamXNG8DRP33MH5krwGDsp8X4xW0AzshKqYhO13kR+rlqB1Slb7/I4p5ZC8jDNT/Q/1n2Zt2Z8TUUmz7VqUDQVH2HJ+PKZsNoyqMqBDJ/bbKL1yCB6GjgaDQnFdKZNHx54fAZp28+Q50j46ivPWYVEeuMuF6aF7qlFICV8WczNIO/qjxsSdMsrFuNMNpJ3m/Eq0mY6vQ2OoxZs1pl1hcLUl8rsZIevgvSzSWkK8P/PQpHhjiIK51b1NWtiWPN++hUuPeA9C+/u3F5m9crzD/ZFLTuQ4j7/Rmwbq5Nhtzlr8ElYk5VAkod1lbOwZ3UHDATL0K3iuTEApzULeRP21YKLv0BIeBABHy7QVyffMalS8bHAC/et8fGnF9yTE4ACwx7ZoiVfhmlsIPWRejm6lyLYXkuWqNK5lHGFwOJk3dhkwWNaYJjbahmKoLybQWYSB2XLsKUEOicao2HFbR95DA0+0T+O6xM5qQDHL5R/z3g=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: VDKA/Notify
    tags: true

script:
  - xcodebuild -project $FRAMEWORK_NAME.xcodeproj -target $FRAMEWORK_NAME -sdk $SDK ONLY_ACTIVE_ARCH=NO
